name: CI/CD pipeline

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        java-version: [17.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          yarn -v
          yarn

      - name: Set up Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          sudo apt-get install -y android-sdk
          echo "ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/Android/Sdk/platform-tools" >> $GITHUB_ENV

      - name: Run Tests
        run: yarn test --coverage

      - name: Verify Node.js and Java Versions
        run: |
          node -v
          java --version

      - name: Build Android Project
        run: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease -Dorg.gradle.jvmargs="-Xmx4096m"

      - name: Upload APK to GitHub Release
        if: github.ref == 'refs/heads/master'
        uses: ncipollo/release-action@v1
        with:
          artifacts: android/app/build/outputs/apk/release/app-release.apk
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tag: "v${{ github.run_number }}"
          name: "Release ${{ github.run_number }}"
          prerelease: false

      - name: Provide APK Download Link
        if: github.ref == 'refs/heads/master'
        run: echo "APK uploaded successfully. Check the latest release for the download link."
